//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string savedNoiseFileLocation {
            get {
                return ((string)(this["savedNoiseFileLocation"]));
            }
            set {
                this["savedNoiseFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string savedLogFileLocation {
            get {
                return ((string)(this["savedLogFileLocation"]));
            }
            set {
                this["savedLogFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string savedComPort {
            get {
                return ((string)(this["savedComPort"]));
            }
            set {
                this["savedComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int savedBaudRate {
            get {
                return ((int)(this["savedBaudRate"]));
            }
            set {
                this["savedBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int savedDataBits {
            get {
                return ((int)(this["savedDataBits"]));
            }
            set {
                this["savedDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string savedStopBits {
            get {
                return ((string)(this["savedStopBits"]));
            }
            set {
                this["savedStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string savedParity {
            get {
                return ((string)(this["savedParity"]));
            }
            set {
                this["savedParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XOnXOff")]
        public string savedHandshake {
            get {
                return ((string)(this["savedHandshake"]));
            }
            set {
                this["savedHandshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string savedIPAddress {
            get {
                return ((string)(this["savedIPAddress"]));
            }
            set {
                this["savedIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7777")]
        public string savedPort {
            get {
                return ((string)(this["savedPort"]));
            }
            set {
                this["savedPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K2700")]
        public string savedInstrumentName {
            get {
                return ((string)(this["savedInstrumentName"]));
            }
            set {
                this["savedInstrumentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4093987")]
        public string savedInstrumentSerial {
            get {
                return ((string)(this["savedInstrumentSerial"]));
            }
            set {
                this["savedInstrumentSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Weiss WLK100")]
        public string savedChamberName {
            get {
                return ((string)(this["savedChamberName"]));
            }
            set {
                this["savedChamberName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("444444")]
        public string savedChamberSerial {
            get {
                return ((string)(this["savedChamberSerial"]));
            }
            set {
                this["savedChamberSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Simpati\\SIMPROG")]
        public string savedChamberProgramFilePath {
            get {
                return ((string)(this["savedChamberProgramFilePath"]));
            }
            set {
                this["savedChamberProgramFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Simpati\\MEASURE")]
        public string savedChamberArchiveFilePath {
            get {
                return ((string)(this["savedChamberArchiveFilePath"]));
            }
            set {
                this["savedChamberArchiveFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoData")]
        public string savedChamberProgramFileName {
            get {
                return ((string)(this["savedChamberProgramFileName"]));
            }
            set {
                this["savedChamberProgramFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoData")]
        public string savedChamberArchiveFileName {
            get {
                return ((string)(this["savedChamberArchiveFileName"]));
            }
            set {
                this["savedChamberArchiveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoData")]
        public string savedTestStartTime {
            get {
                return ((string)(this["savedTestStartTime"]));
            }
            set {
                this["savedTestStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoData")]
        public string savedTestFinishedTime {
            get {
                return ((string)(this["savedTestFinishedTime"]));
            }
            set {
                this["savedTestFinishedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chamber controlled")]
        public string savedTestSignalMode {
            get {
                return ((string)(this["savedTestSignalMode"]));
            }
            set {
                this["savedTestSignalMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11002¶1¶1¶")]
        public string chamberTemperature {
            get {
                return ((string)(this["chamberTemperature"]));
            }
            set {
                this["chamberTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11002¶1¶2¶")]
        public string chamberHumidity {
            get {
                return ((string)(this["chamberHumidity"]));
            }
            set {
                this["chamberHumidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14003¶1¶4¶")]
        public string chamberDigitalOut {
            get {
                return ((string)(this["chamberDigitalOut"]));
            }
            set {
                this["chamberDigitalOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14003¶1¶1¶")]
        public string chamberStartStatus {
            get {
                return ((string)(this["chamberStartStatus"]));
            }
            set {
                this["chamberStartStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10024¶1¶")]
        public string chamberArchivePath {
            get {
                return ((string)(this["chamberArchivePath"]));
            }
            set {
                this["chamberArchivePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10026¶1¶")]
        public string chamberProgramPath {
            get {
                return ((string)(this["chamberProgramPath"]));
            }
            set {
                this["chamberProgramPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19012¶1¶")]
        public string chamberArchiveName {
            get {
                return ((string)(this["chamberArchiveName"]));
            }
            set {
                this["chamberArchiveName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19031¶1¶")]
        public string chamberProgramName {
            get {
                return ((string)(this["chamberProgramName"]));
            }
            set {
                this["chamberProgramName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10006¶1¶")]
        public string chamberName {
            get {
                return ((string)(this["chamberName"]));
            }
            set {
                this["chamberName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int savedScanRate {
            get {
                return ((int)(this["savedScanRate"]));
            }
            set {
                this["savedScanRate"] = value;
            }
        }
    }
}
